include:
  - project: additi/external/gitlab-templates-common
    file: .gitlab-ci-common.yml
    ref: master

.variables-unrestricted: &variables-unrestricted
  # Common
  # define Gitlab variable which contain container image repository (registry): $REPOSITORY_UNRESTRICTED or $REPOSITORY_RESTRICTED
  REPOSITORY: $REPOSITORY_UNRESTRICTED
  # define Gitlab variable which contains image tag, based on $CI_COMMIT_TAG or $CI_COMMIT_SHORT_SHA
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  # Push
  # define Gitlab variable which contains Google Application Credentials: $GOOGLE_APPLICATION_CREDENTIALS_UNRESTRICTED or $GOOGLE_APPLICATION_CREDENTIALS_RESTRICTED
  GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_UNRESTRICTED
  # Deploy
  # define branch on platform repository to use : unrestricted or restricted
  BRANCH: unrestricted

.variables-restricted: &variables-restricted
  # Common
  # define Gitlab variable which contain container image repository (registry): $REPOSITORY_UNRESTRICTED or $REPOSITORY_RESTRICTED
  REPOSITORY: $REPOSITORY_RESTRICTED
  # define Gitlab variable which contains image tag, based on $CI_COMMIT_TAG or $CI_COMMIT_SHORT_SHA
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  # Push
  # define Gitlab variable which contains Google Application Credentials: $GOOGLE_APPLICATION_CREDENTIALS_UNRESTRICTED or $GOOGLE_APPLICATION_CREDENTIALS_RESTRICTED
  GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_RESTRICTED
  # Deploy
  # define branch on platform repository to use : unrestricted or restricted
  BRANCH: restricted

stages:
  - build
  - push
  - scan_image
  - deploy

build:
  extends: .build
  variables:
    # Set build-time variables
    # 20 indexes can be used: DOCKER_BUILD_ARG_01 to DOCKER_BUILD_ARG_20
    # DOCKER_BUILD_ARG_01: KEY=VALUE

    # Pass secret information to be used in the Dockerfile for building docker images 
    # in a safe way that will not end up stored in the final image.
    # References:
    # - https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information
    # You can add CI/CD variable of type `file` and by path to the temp file, example: ${CI_PROJECT_DIR}.tmp/[KEY]
    # References:
    # - https://docs.gitlab.com/ee/ci/variables/index.html#add-a-cicd-variable-to-a-project
    # - https://docs.gitlab.com/ee/ci/variables/index.html#add-a-cicd-variable-to-a-group
    # 20 indexes can be used: DOCKER_BUILD_SECRET_01 to DOCKER_BUILD_SECRET_20
    # DOCKER_BUILD_SECRET_01: id=google_application_credentials_bucket,src=${CI_PROJECT_DIR}.tmp/GOOGLE_APPLICATION_CREDENTIALS_BUCKET

    # Name of the Dockerfile (Default is 'build/Dockerfile')
    DOCKER_BUILD_DOCKERFILE: build/Dockerfile
    # The Docker build context refers to the files and directories that will be available to the Docker engine when you run docker build
    DOCKER_BUILD_CONTEXT: .

# test-unit:
#   stage: tests
#   script:
#     - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#     - docker pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
#     # - `docker run` your container here
#     # - `docker exec` your tests here
#   # Extract code coverage to get the info in gitlab : https://docs.gitlab.com/ee/ci/yaml/#coverage
#   # coverage: /^\s*Lines:\s*\d+.\d+\%/

push-dev:
  needs: [build]
  extends: .push
  variables:
    <<: *variables-unrestricted
  only :
    - develop

deploy-dev1:
  needs: [push-rec]
  extends: .deploy
  variables:
    <<: *variables-unrestricted
    # insert the name of the helm yaml values file for this platform
    VALUES_FILENAME: ""
  only:
    - develop

push-rec:
  needs: [build]
  extends: .push
  variables:
    <<: *variables-unrestricted
  when: manual
  except :
    - tags
    - master
    - develop

scan_image-rec:
  needs: [push-rec]
  extends: .scan_image
  allow_failure: true
  variables:
    <<: *variables-unrestricted
  except:
    - tags
    - master
    - develop

deploy-rec1:
  needs: [push-rec]
  extends: .deploy
  variables:
    <<: *variables-unrestricted
    # insert the name of the helm yaml values file for this platform
    VALUES_FILENAME: ""
  when: manual
  except:
    - tags
    - master
    - develop

push-prod-preprod:
  needs: [build]
  extends: .push
  variables:
    <<: *variables-restricted
  only :
    - tags

scan_image-prod-preprod:
  needs: [push-prod-preprod]
  extends: .scan_image
  allow_failure: true
  variables:
    <<: *variables-restricted
  only:
    - tags

deploy-preprod:
  needs: [push-prod-preprod]
  extends: .deploy
  variables:
    <<: *variables-restricted
    # insert the name of the helm yaml values file for this platform
    VALUES_FILENAME: ""
  only:
    - tags

deploy-prod:
  needs: [push-prod-preprod]
  extends: .deploy
  variables:
    <<: *variables-restricted
    # insert the name of the helm yaml values file for this platform
    VALUES_FILENAME: ""
  when: manual
  allow_failure: false
  only:
    - tags

