image: docker:20.10

services:
  - docker:20.10-dind

before_script:
  - export PROJECT_NAME=${CI_PROJECT_NAME/content-app-/}

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - tags
  script:
    # Install gcloud sdk
    - apk upgrade && apk add --no-cache curl openssl jq python3
    - curl -s https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
    - mkdir -p /usr/local/gcloud && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz && /usr/local/gcloud/google-cloud-sdk/install.sh --quiet
    - export PATH=$PATH:/usr/local/gcloud/google-cloud-sdk/bin

    # Configure Docker to use the project registry (Google Artifact Registry)
    - gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
    - gcloud auth configure-docker ${REPOSITORY%%/*} --quiet

    # Build & Push
    - docker build -t $REPOSITORY/${PROJECT_NAME}:$CI_COMMIT_TAG -f build/Dockerfile .
    - docker push $REPOSITORY/${PROJECT_NAME}:$CI_COMMIT_TAG
    - docker images

deploy-preprod:
  stage: deploy
  only:
    - tags
  script:
    - apk add git
    - git clone "https://$CI_CUSTOM_USER:$CI_CUSTOM_USER_TOKEN@gitlab.com/additi/internal/dsi-devops-engineers/platform_configuration_helm_devops-demo.git"
    - cd platform_configuration_helm_devops-demo
    - git checkout non-production
    - git config --global user.name "${PROJECT_NAME} CI"
    - git config --global user.email "${PROJECT_NAME}ci@gitlab.com"
    - docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace values-preproduction.yaml app_version $CI_COMMIT_TAG
    - docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace values.yaml image_name $PROJECT_NAME
    - docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace values.yaml repository $REPOSITORY
    - git commit -am "update image preprod tag" && git push origin non-production

deploy-prod:
  stage: deploy
  when: manual
  only:
    - tags
  script:
    - apk add git
    - git clone "https://$CI_CUSTOM_USER:$CI_CUSTOM_USER_TOKEN@gitlab.com/additi/internal/dsi-devops-engineers/platform_configuration_helm_devops-demo.git"
    - cd platform_configuration_helm_devops-demo
    - git config --global user.name "${PROJECT_NAME} CI"
    - git config --global user.email "${PROJECT_NAME}ci@gitlab.com"
    - docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace values-production.yaml app_version $CI_COMMIT_TAG
    - docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace values.yaml image_name $PROJECT_NAME
    - docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace values.yaml repository $REPOSITORY
    - git commit -am "update prod image tag" && git push origin master

